name: Non-Default Branch Push CI (Python)

on:  
  push:
    branches-ignore: [ "main" ]
    paths-ignore: ['README.md']
  pull_request:
    types: ["opened", "reopened", "edited"]
    paths-ignore: ["README.md"]

jobs:
  branch-ci:
    uses: openclimatefix/.github/.github/workflows/nondefault_branch_push_ci_python.yml@main
    secrets: inherit
    with:
      enable_linting: true
      enable_typechecking: true
      tests_folder: tests

